#!/bin/bash

#PBS -N workshop
#PBS -l wd
#PBS -P nf33
#PBS -q express
#PBS -l walltime=0:20:00  
#PBS -l ncpus=1
#PBS -l mem=63GB           
#PBS -l jobfs=10GB        
#PBS -l storage=gdata/nf33+gdata/fs38+gdata/oi10+gdata/xp65+gdata/hh5+gdata/ct11+scratch/nf33
#PBS -o ./output_tree_log
#PBS -e ./error_tree_log

module use /g/data/xp65/public/modules
module load conda/access-med

ilamb-tree-generator --datasets cmip_models.yml --ilamb_root ILAMB_ROOT  
